---
- set_fact:
    bind_service_name: "{{ rpm_service_name }}"
    bind_user: "{{ rpm_user_name }}"
    bind_packages: "{{ rpm_packages }}"
    bind_config_path: "{{ rpm_config_path }}"
    bind_config_dir: "{{ rpm_config_dir }}"
    bind_run_path: "{{ rpm_run_path }}"
    bind_log_path: "{{ rpm_log_path }}"
  when: ansible_os_family == "RedHat"

- set_fact:
    bind_service_name: "{{ deb_service_name }}"
    bind_user: "{{ deb_user_name }}"
    bind_packages: "{{ deb_packages }}"
    bind_config_path: "{{ deb_config_path }}"
    bind_config_dir: "{{ deb_config_dir }}"
    bind_run_path: "{{ deb_run_path }}"
    bind_log_path: "{{ deb_log_path }}"
  when: ansible_os_family == "Debian"

- name: bind | Install deb packages
  package:
    pkg:  "{{ item }}"
    state: installed
  with_items: bind_packages

- name: bind | Add bind user
  group:
    name: "{{ bind_user }}"
    state: present

- name: bind | Add bind group
  user:
    name: "{{ bind_user }}"
    group: "{{ bind_user }}"
    createhome: no
    home: /tmp
    shell: /bin/true
    state: present

- name: bind | Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bind_user }}"
    group: "{{ bind_user }}"
    mode: 0755
  with_items:
    - "{{ bind_config_path }}"
    - "{{ bind_config_dir }}"
    - "{{ bind_run_path }}"
    - "{{ bind_log_path }}"

- name: bind | Update named options
  template:
    src: named.conf.options.j2
    dest: "{{ bind_config_path }}"
    owner: "{{ bind_user }}"
    group: "{{ bind_user }}"
  register: bind_setup

- name: Update rndc key
  template:
    src: rndc.key.j2
    dest: "{{ bind_config_dir }}/rndc.key"
    mode: 0644
    owner: "{{ bind_user }}"
    group: "{{ bind_user }}"


- name: Enable bind systemd
  service:
    name: "{{ bind_service_name }}"
    state: started
    enabled: yes

- name: Restart bind when config changed
  service:
    name: "{{ bind_service_name }}"
    state: restarted
  when: bind_setup.changed
