---
- name: bind | Install packages
  package:
    pkg:  "{{ item }}"
    state: installed
  with_items:
    - bind9
    - bind9utils
    - dnsutils

- name: Update named options
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  register: bind_setup

- name: Add log directory
  file:
    path: /var/log/bind
    state: directory
    owner: bind
    group: bind
    mode: 0755

- name: Update rndc key
  template:
    src: rndc.key.j2
    dest: /etc/bind/rndc.key
    mode: 0644

- name: Enable bind systemd
  service:
    name: bind9
    state: started
    enabled: yes

- name: Restart bind when config changed
  service:
    name: bind9
    state: restarted
  when: bind_setup.changed

